# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_subject_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Section'),
        ),
    ]
