# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_subject_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Section'),
        ),
    ]
