# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170811_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
